upstream backend_api {
    server app:3000; # Docker compose မှာ replicas သုံးရင် app ဆိုတဲ့ နာမည်က ၃ လုံးလုံးကို ကိုယ်စားပြုတယ်
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React Router - SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend_api/; # Backend service ဆီ ပို့မယ်
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
