services:
  app:
    build: .
    container_name: crud_app
    ports:
      - "3000:3000"
    env_file:
      - .env        # ← .env file ကနေ ယူတယ်
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: crud_db
    env_file:
      - .env        # ← .env file ကနေ ယူတယ်
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout:  5s
      retries:  5
    restart: unless-stopped

volumes:
  pgdata: